# Generated by Django 5.2.4 on 2025-10-19 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DriftMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feature_drifts', models.JSONField(default=dict)),
                ('prediction_drift', models.JSONField(default=dict)),
                ('concept_drift', models.JSONField(default=dict)),
                ('overall_drift_score', models.FloatField()),
                ('drift_detected', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelregistry')),
            ],
        ),
        migrations.CreateModel(
            name='DataQualityMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('missing_counts', models.JSONField(default=dict)),
                ('missing_percentages', models.JSONField(default=dict)),
                ('outlier_counts', models.JSONField(default=dict)),
                ('type_mismatches', models.JSONField(default=dict)),
                ('schema_violations', models.JSONField(default=dict)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelregistry')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('DATA_QUALITY', 'Data Quality Issue'), ('PERFORMANCE', 'Performance Degradation'), ('DRIFT', 'Data/Concept Drift'), ('INFRASTRUCTURE', 'Infrastructure Issue')], max_length=20)),
                ('level', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelregistry')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('false_positive_rate', models.FloatField(blank=True, null=True)),
                ('false_negative_rate', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('r_squared', models.FloatField(blank=True, null=True)),
                ('mape', models.FloatField(blank=True, null=True)),
                ('avg_latency_ms', models.FloatField(blank=True, null=True)),
                ('p95_latency_ms', models.FloatField(blank=True, null=True)),
                ('p99_latency_ms', models.FloatField(blank=True, null=True)),
                ('error_rate', models.FloatField(blank=True, null=True)),
                ('sample_size', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelregistry')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.JSONField()),
                ('prediction', models.JSONField()),
                ('actual_value', models.JSONField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('missing_values', models.JSONField(default=dict)),
                ('outliers', models.JSONField(default=dict)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.modelregistry')),
            ],
        ),
    ]
