# Generated by Django 5.2.4 on 2025-11-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['model', '-timestamp'], name='api_alert_model_i_49e8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type'], name='api_alert_alert_t_e1fa27_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['level'], name='api_alert_level_cdf760_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualitymetric',
            index=models.Index(fields=['model', '-timestamp'], name='api_dataqua_model_i_2d0ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='driftmetric',
            index=models.Index(fields=['model', '-timestamp'], name='api_driftme_model_i_141fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='modelregistry',
            index=models.Index(fields=['name'], name='api_modelre_name_f102a4_idx'),
        ),
        migrations.AddIndex(
            model_name='modelregistry',
            index=models.Index(fields=['created_at'], name='api_modelre_created_731f20_idx'),
        ),
        migrations.AddIndex(
            model_name='performancemetric',
            index=models.Index(fields=['model', '-timestamp'], name='api_perform_model_i_e523c1_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['model', '-timestamp'], name='api_predict_model_i_871d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['timestamp'], name='api_predict_timesta_73540e_idx'),
        ),
    ]
